import pytest
from src.agents.supervisor_agent import dispatch_synthesis, NotReadyError

def init_state(**kwargs):
    s = {
        "case_id": "c1", "trace_id": "t1", "control_flags": {}, "active_tier": "", 
        "dispatched_agents": [], "completed_agents": [], "dead_end_detected": False, 
        "hitl_attempt_count": 0, "terminal_state": ""
    }
    s.update(kwargs)
    return s

@pytest.mark.asyncio
async def test_synthesis_waits_for_all_primary_and_specialist_agents():
    """The threat_attribution node MUST block until all currently dispatched agents have written their output to Neo4j."""
    state = init_state(dispatched_agents=["a1", "a2"], completed_agents=["a1"])
    with pytest.raises(NotReadyError):
        await dispatch_synthesis(state)

@pytest.mark.asyncio
async def test_synthesis_fires_only_after_full_completion():
    """Once all dispatched agents complete, synthesis MUST fire."""
    state = init_state(dispatched_agents=["a1", "a2"], completed_agents=["a1", "a2"])
    result = await dispatch_synthesis(state)
    assert "timeline_reconstruction" in result["dispatched_agents"]

@pytest.mark.asyncio
async def test_tr_dispatched_strictly_before_ta():
    """Timeline Reconstruction (TR) MUST execute before Threat Attribution (TA)."""
    # Represented by sequential insertion in dispatched agents
    state = init_state(dispatched_agents=["a1"], completed_agents=["a1"])
    result = await dispatch_synthesis(state)
    assert result["dispatched_agents"] == ["timeline_reconstruction", "threat_attribution"]

@pytest.mark.asyncio
async def test_ta_receives_tr_output_as_input():
    """Threat Attribution MUST receive the specific graph sub-topology generated by Timeline Reconstruction."""
    state = init_state(dispatched_agents=["a1"], completed_agents=["a1"])
    result = await dispatch_synthesis(state)
    assert "timeline_edges" in result["threat_attribution_input"]
